name: restler
description: A beautiful and powerful REST client app for Android.
version: 0.17.6+77

environment:
  sdk: ">=2.10.0 <3.0.0"
  flutter: ">=1.24.0-0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  fakedart:
    git:
      url: git://github.com/tiagohm/fakedart.git
      ref: 4b8efa0aae70d87947d85958c4516f4f5f006740
  sqler:
    git:
      url: git://github.com/tiagohm/sqler.git
      ref: cae86d7b48038dd7ef967addb3fa1e9af2b1468b
  badges: 1.1.4
  connectivity: 2.0.2
  datetime_picker_formfield: 1.0.0
  encrypt: 4.1.0
  event_bus: 1.1.1
  file_picker: 2.1.0
  flushbar: 1.10.4
  flutter_bloc: 6.1.1
  flutter_inapp_purchase: 3.0.0
  flutter_markdown: 0.5.1
  flutter_svg: 0.19.2+1
  flutter_typeahead: 1.8.8
  hive: 1.4.4+1
  kiwi: 2.1.1
  path_provider: 1.6.24
  permission_handler: 5.0.1+1
  restio: 0.10.11
  restio_cache: 0.1.2+1
  rxdart: 0.24.1
  sqflite: 1.3.2+1
  syntax_highlighter: 0.1.1
  url_launcher: 5.7.10
  uuid: 2.2.2
  yaml: 2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  tradutor: 0.9.2

flutter:
  uses-material-design: true
  fonts:
    - family: Mdi
      fonts:
        - asset: assets/fonts/Mdi.ttf
  assets:
    - assets/images/logo.svg
